name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Vet
        run: go vet ./cmd/... ./internal/...

      - name: Test
        run: go test ./internal/...
